# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.detect_missing_cpp <- function(intensity, gap = 1L, noise = 100) {
    .Call(`_MetaboDeconv_detect_missing_cpp`, intensity, gap, noise)
}

electronic_denoising_cpp <- function(msms) {
    .Call(`_MetaboDeconv_electronic_denoising_cpp`, msms)
}

